### PR TITLE
Add "precompiled" mode

### PR DESCRIPTION
**Pull request by ISSOtm**
**PR has been refocused after some of the changes were merged** — see https://github.com/bbbbbr/png2hicolorgb/pull/3#issuecomment-1681293637 for the new "OP".

---

The branch name should suggest what this was originally meant to be; however, the RGBDS example build script failed on argument parsing, so I dug into that, and one thing leading to another, here we are :')

Note that what pertains to the RGBDS example is only the bare minimum needed to make it compile; the code itself is, um, in need of an overhaul. I'm submitting the PR before that's completed, so that the changes to the C code can be reviewed in parallel.

Only the arg parsing was overhauled (tried to keep it compact), as the rest of the code is far too discouraging. (I'd feel more motivated rewriting it from scratch than trying to hammer what's there into shape.)

### CODE REVIEW

**Comment by ISSOtm** [comment]
Oh, additionally: it was mentioned that the GBDK example was improved somehow. Was that ported to the RGBDS example as well?

**Comment by bbbbbr** [comment]
Thanks for opening this. Since there are a lot of changes, ideally I'd prefer to evaluate and integrate them as separate groups (as PRs or I can cherry pick merge them) in the following priority:
- RGBDS example improvements / modernization
- Potential RGBDS compatible metadata export (image height, tile count, perhaps bank assignment if useful)
- Bug Fixes (if any)
- Build Fixes
- Feature Improvements (if any)
- Stylisitc changes (to be forthright, I'll have to think about whether I'd want to merge them)

Disclaimer: now that the initial version of this project is out usable I may move slower on it (unless showstopper bugs turn up) since I was hoping to rotate out to a couple other projects. 


> Oh, additionally: it was mentioned that the GBDK example was improved somehow. Was that ported to the RGBDS example as well?

Improvements the GBDK example has (they have not been ported to the RGBDS example):
- Supports scrolling on the Y axis (via an SCY based offset into the Palette data). Some additional metadata (tile height) needs to be exported for that to work if tile deduplication mode is used (since then height cannot be derived from tile count)
- The scanline palette update completes a little sooner than the original by using di+halt instead of a busy loop to wait for hblank (https://github.com/bbbbbr/png2hicolorgb/blob/251028424ae79ed241d30ba63c57d84fceddd1f3/example_gbdk/src/gbc_hicolor.c#L83) and an extra preload. IIRC toxa mentioned this should allow it to work without breaking timing with up to 10 sprites present on the scanline.

**Comment by ISSOtm** [comment]
> Since there are a lot of changes, ideally I'd prefer to evaluate and integrate them as separate groups

GitHub's UI allows viewing and reviewing specific ranges of commits; the earlier commits were the "improvements" ones, so you can review those only. If you want to merge them separately, we can review them and then I'll split those commits off into a separate PR.

The reason why I published all the changes together, is that I felt it'd make more sense to submit them together with the rationale for the changes (i.e. the RGBDS example improvements).

> * Feature Improvements (if any)

That's what you could consider the standardised arg parsing to be. It makes the tool more predictable, of course.

> * Stylisitc changes (to be forthright, I'll have to think about whether I'd want to merge them)

Yeah, I figure you don't know all of this code, so I kept changes to a reasonable minimum. If I had done anything stylistic, it'd have been setting up `clang-format`, but I didn't bother given how much noise it'd add to the PR overall.

> Disclaimer: now that the initial version of this project is out usable I may move slower on it (unless showstopper bugs turn up) since I was hoping to rotate out to a couple other projects.

Well, I did all of this since you expressly requested help in getting the RGBDS example updated.

> * Supports scrolling on the Y axis (via an SCY based offset into the Palette data). Some additional metadata (tile height) needs to be exported for that to work if tile deduplication mode is used (since then height cannot be derived from tile count)

Yeah, I'm working on exporting any necessary metadata.

> * The scanline palette update completes a little sooner than the original [...]

I timed some experimental changes, and they all complete after the beginning of the following scanline, which means that using interrupts brings no benefit anyway (no "main" code has time to run). Were those timing changes timed?

> IIRC toxa mentioned this should allow it to work without breaking timing with up to 10 sprites present on the scanline.

Considering the max penalties from individual OBJs, I'm skeptical of that—it seems like the safe maximum is only in the low single digits. Do you have any ROMs this was tested on?

**Comment by bbbbbr** [comment]
Yes, as mentioned above I'll prioritize updates to the RGBDS example and metadata for it (and correct, I did say PRs for updates to it were welcome). Other things are on as time permits and maybe merge basis.

I've merged in the RGBDS example changes + mentioned credit for them in the Readme

**Comment by bbbbbr** [comment]
6 seems to be the sprite limit for the current GBDK example, it can't quite make timing for 7. Left/Right to adjust number of sprites in the ROM.
[hicolor_pic_sprite.gbc.zip](https://github.com/bbbbbr/png2hicolorgb/files/12328542/hicolor_pic_sprite.gbc.zip)

- With the updated version in the gbdk example the last palette write is at dot 8.
- With the classic version the last palette write alternates between dot 22 and 28
- It doesn't use scanline interrupts to jump to the ISR, just to wake up and begin the writes a little sooner than the previous busy loop (starting at dot 254 instead of 264 / 270).

**Comment by ISSOtm** [comment]
Okay, I've rebased the changes.

## Arg processing

The arg processing standardisation required one change—`-L=x` has to be `-L x` instead. I don't think that should be a big deal, but worst case I can hack in handling for that.

The point of that change is to make arg handling more consistent with other applications, and thus more predictable / less surprising, including within the application itself (see the inconsistency between `-L=` and `-o ` for an example).

I tried to emulate GNU arg handling, which is mostly a better superset of POSIX arg handling. `getopt_long` normally handles all of this, but it's non-standard, so I figured you'd prefer something portable. (If not, let me know and I'll simply switch the PR to that.)

The other benefit is that adding new options is simpler, as shown by the `--precompiled` flag. (Though I may end up discarding that change, depending on the results of the experiment.)

**Comment by ISSOtm** [comment]
Still lacking a little polish, but look at this beauty!

image

**Comment by ISSOtm** [comment]
So, this PR is two things now, I guess:

1. CLI interface overhaul / harmonisation
2. Introduction of `--precompile` to further increase the number of OBJs that can be overlaid without breakage

Let me know if any of these halves are unacceptable to you. I'll split the PR accordingly. (I don't want to do it preemptively, because I'd rather not rebase the `--precompile` change if I can avoid it.)

**Comment by bbbbbr** [comment]
Thanks for the work on this. I spent some time going over the changes, some work for me and a some don't- comments below so they're all in one place.

If what is outlined below is ok then I can do the merging (with a few edits) to save you time, or you're welcome to do the rebase/etc if you prefer. If you're not into it we could try to discuss further to arrive at something that does.

* **Yes:**  `Fix missing headers in include files` 2bc1067

* **Yes with minor changes:**  `Enable and fix compiler warnings` 193da0f
  - I think if these are changed to unsigned then it needs a different way to clamp the case where `y_line` would normally evaluate to `-1`
    - (scanline 0, left side of the image. this is because it tries to have the 80x2 pixel box go from scanline -1 to 0). 
```
hicolor.c @845 and @892 (changed version)
  - s32 y_line = (y*2+y2-y_offset);
  + unsigned int y_line = (y*2+y2-y_offset);
     if ((y_line < image_y_min) || (y_line > image_y_max)) 
```
  - Otherwise it might only work... accidentally? (due to unsigned wraparound exceeding image_y_max). I prob should have added a more explicit comment about that there. So maybe adding this above the assignment in both locations:
```
if (y_offset > (y*2+y2))` continue;
```

* **No:** `Remove unused functions in files.c` a9653c7

* **Yes:** `Overhaul logging system` e57be09

* **No:** `Overhaul option handling` bd8efdc

* **Yes:** `Switch to interrupt-based setup` 59707fd

* **No:** `Remove accessor functions for options` 396a2ea

* **Yes with Changes:** `Experiment with "pre-compiled" mode` cbe311c
  - Flag name "--precompiled"
  - It should be a separate example (or selectable between the two export types within the example, but that might get cluttered?) so that the original mode still has an example
  - There should be a brief note (could be example Readme or main one) about how it's different in implementation, size & speed
  - Exporting the palette code should be a separate function (ExportPalettesPrecompiled()) than the regular palette export
  - Maybe use constants for the GB opcodes instead of raw hex values (SM83_HALT, SM83_LD_HL_B ...)

* Yes: `Apply "preloading" optimisation to --precompile` 774c12d

**Comment by bbbbbr** [comment]
I made a branch with the changes selectively merged in and the above edits. For review:
https://github.com/bbbbbr/png2hicolorgb/compare/main...ISSOtm_merges

**Comment by ISSOtm** [comment]
Ugh, my apologies, I meant to reply earlier, but I've had trouble staying on top of all my notifications.

I'll get to applying your suggested modifications in a moment. They look good to me.

If I may, what's your rationale for rejecting the "option handling standardisation" change? The goal of that commit is to make the various options more consistent with themselves and predictable (consistent with other CLI tools, typically `getopt_long`).
I did realise that it breaks the previous `-L=n` handling (treating that as `-L =1`), but I see no harm in handling that in a backwards compatible manner; that should be as simple as checking if the first character is a `=` before "splitting", and skipping it if so. (No real harm, considering what parameters these options expect.)

I haven't looked at the commit range you just posted yet, given the above conversation. Should I?

**Comment by bbbbbr** [comment]
> Ugh, my apologies, I meant to reply earlier, but I've had trouble staying on top of all my notifications.

No worries, always a lot going on and other priorities. :+1: 

> I'll get to applying your suggested modifications in a moment. They look good to me.

I ended up already making the suggested changes when I merged the YES commits. So no need to do that.
https://github.com/bbbbbr/png2hicolorgb/compare/main...ISSOtm_merges

Also, there's a commit f1d2ade1cfb56efd0713f5ff4aed87154ca9b820 after that in a further branch (just to keep it separate for the moment):
https://github.com/bbbbbr/png2hicolorgb/compare/main...ISSOtm_merges_post

> If I may, what's your rationale for rejecting the "option handling standardisation" change? The goal of that commit is to make the various options more consistent with themselves and predictable (consistent with other CLI tools, typically `getopt_long`). I did realise that it breaks the previous `-L=n` handling (treating that as `-L =1`), but I see no harm in handling that in a backwards compatible manner; that should be as simple as checking if the first character is a `=` before "splitting", and skipping it if so. (No real harm, considering what parameters these options expect.)

I'm not into it the changes for both usage style and implementation reasons, but it's not worth going into in detail.

> I haven't looked at the commit range you just posted yet, given the above conversation. Should I?

Just to recap from above - you can check this branch where I've merged all the YES commits:
https://github.com/bbbbbr/png2hicolorgb/compare/main...ISSOtm_merges

And this extra commit f1d2ade1cfb56efd0713f5ff4aed87154ca9b820 for the improved Left/Right & etc options in this branch:
https://github.com/bbbbbr/png2hicolorgb/compare/main...ISSOtm_merges_post

**Comment by bbbbbr** [comment]
And lastly... If the branches mentioned above look ok then I'll merge those into main.

**Comment by bbbbbr** [comment]
Last week I merged the changes as described here: https://github.com/bbbbbr/png2hicolorgb/pull/3#issuecomment-1703206416

So the precompiled support is now included in main. There are also separate examples for both modes and toolchains/languages.

**Comment by ISSOtm** [comment]
Yeah, sorry, I got caught up in other PRs. I don't know if all the of "meat" of this PR got merged upstream, but frankly, you've already done a lot of work integrating at least most of it, so let's drop this.

And, thank you for said work!

**Comment by bbbbbr** [comment]
Same, thanks for all your work and patience on this on this too!
Looking forward to putting out a new release in a while with the improvements.

**Pull request closed without merging**
